// Import React
import React from "react";

// Import Spectacle Core tags
import CodeSlide from "spectacle-code-slide";

function escapeHtml(unsafe) {
    return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
         .replace(/'/g, "&#039;");
 }

export default (
    <CodeSlide transition={["slide"]}
            bgColor="quartenary"
            lang="markup"
            code={escapeHtml(
`<MPD xmlns="urn:mpeg:dash:schema:mpd:2011"
  minBufferTime="PT1.500S"
  type="static"
  mediaPresentationDuration="PT0H19M22.167S"
  maxSegmentDuration="PT0H0M4.000S"
  profiles="urn:mpeg:dash:profile:full:2011">

  <ProgramInformation>
    <Title>uvic_dji.mpd generated by GPAC</Title>
  </ProgramInformation>

  <Period duration="PT0H19M22.167S">
    <AdaptationSet
      segmentAlignment="true"
      maxWidth="2704" maxHeight="1520"
      maxFrameRate="24"
      par="2704:1520"
      lang="und">

      <Representation
        id="1" mimeType="video/mp4"
        codecs="avc3.4D4032"
        width="2704" height="1520"
        frameRate="24" sar="1:1"
        startWithSAP="1" bandwidth="2472846">

        <SegmentList timescale="24000"
          duration="96000">
          <SegmentURL media="seg_1.m4s" />
          <SegmentURL media="seg_2.m4s" />
          <SegmentURL media="seg_3.m4s" />
          ...
          <SegmentURL media="seg_291.m4s" />
        </SegmentList>

        <SegmentList timescale="24000"
          duration="96000">
          <SegmentURL media="seg.m4s"
            range="0-499" />
          <SegmentURL media="seg.m4s"
            range="500-999" />
          <SegmentURL media="seg.m4s"
            range="1000-1499" />
          ...
          <SegmentURL media="seg.m4s"
            range="6839000-6839499"/>
        </SegmentList>

        <SegmentList timescale="24000"
          duration="96000">
          <Initialization src="sidx.mp4" />
          <SegmentURL media="seg.m4s" />
        </SegmentList>

        <SegmentList timescale="24000"
          duration="96000">
          <BaseURL media="seg.m4s" init="0-500" />
        </SegmentList>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>`)}
        ranges={[
            { loc: [0, 1], title: "Media Presentation Description" },
            { loc: [0, 6], note: "MPD tag"},
            { loc: [3, 5], note: "Durations"},
            { loc: [7, 10], note: "Program information"},
            { loc: [11, 18], note: "Period tag and an adaptation set"},
            { loc: [19, 25], note: "A representation"},
            { loc: [26, 34], note: "A segment list using seperate files"},
            { loc: [35, 47], note: "A segment list using range-requests"},
            { loc: [48, 53], note: "A segment list using an index"},
            { loc: [54, 58], note: "A segment with index built in"},
        ]}
    />
);

